// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocInkDataLayer;

namespace PocInkDAL.Migrations
{
    [DbContext(typeof(PocInkDBContext))]
    partial class PocInkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PocInkDataLayer.Models.InkDrawing", b =>
                {
                    b.Property<Guid>("DrawingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DrawingName");

                    b.Property<string>("Title");

                    b.Property<string>("UserId");

                    b.HasKey("DrawingId");

                    b.ToTable("InkDrawings");
                });

            modelBuilder.Entity("PocInkDataLayer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("HashedPassword");

                    b.Property<string>("Role");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15215b0e-ca81-4ba7-b829-2fe2e397a6a1"),
                            Email = "Shakespeare@yahoo.com",
                            HashedPassword = "MXxgg2ygTwY7KlhyeTZrrgHA0DjYg2r93SKt1pmfASI=",
                            Role = "Admin",
                            UserName = "William"
                        },
                        new
                        {
                            Id = new Guid("04d38a16-924f-47a8-a53d-0f9b3eebc7df"),
                            Email = "John@yahoo.com",
                            HashedPassword = "JUZ3HfuAnPDLx5YkeEDcLoe/JXTgre2BUai1nhQ+rWA=",
                            Role = "",
                            UserName = "John"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
